### PR TITLE
Feat/update at index

### PR DESCRIPTION
**Pull request by jansedlon**
Hey @edmundhung. I am in need to update a list item at a specific index so I tried to implement it. I welcome any suggestions. There's no contribution guide so I tried to scrap the code and came up with this :D

Use case:
I have a list of attachments in a community post. When a user wants to upload a file, I want to immediately insert it into a list with a loading state and when the upload is finished, I want to update the url and state at a specified index.

For now I have done it using remove and insert which works but is suboptimal.

### CODE REVIEW

**Comment by jansedlon** [comment]
Hey @edmundhung. I am in need to update list item at a specific index so I tried to implement it. I welcome any suggestions. There's no contribution guide so I tried to scrap the code and came up with this :D 

Use case:
I have a list of attachments in a community post. When a user wants to upload a file, I want to immediately insert it into a list with a loading state and when the upload is finished, I want to update the url and state at a specified index.

For now I have done it using remove and insert which works but is suboptimal.

**Comment by edmundhung** [comment]
I haven't look into the detail yet. But the update intent should work anywhere, you can point it to the list and update the whole list or point it to a specific index and update the value just like any other field.

**Comment by jansedlon** [comment]
From what I saw, it accepts a list of values. If I try to update a specific index, the field doesn't exist yet.

Example
```
form.insert({
  name: fields.attachments.name,
  value: {
    // ...value
  }
});

// code

fetch().then(() => {
  // I want to update here but the reference to the fieldlist does not have the inserted field
})
```

**Comment by jansedlon** [comment]
This works, but it's meh :D 
```
form.update({
          name: `attachments[${someDeterminedIndex}]`,
          value: {
            // data
          },
        });
```

**Comment by edmundhung** [comment]
How about making `form.update` to accept an optional index? Then you could do this:
```tsx
form.update({
  name: fields.attachments.name,
  index: someDeterminedIndex,
  value: {
    // data
  },
});
```

**Comment by jansedlon** [comment]
Absolutely, that could be the case. However the update logic is much more complex and I'm not sure I'd do it correctly

**Comment by edmundhung** [comment]
Here you go: #555

**Comment by jansedlon** [comment]
Hey, thank you 🙏🙏 Sorry, haven't had time to try out, will tomorrow

**Comment by edmundhung** [comment]
It's all good :) You can try it out on [v1.1.0-pre.0](https://github.com/edmundhung/conform/releases/tag/v1.1.0-pre.0) now.

**Comment by jansedlon** [comment]
@edmundhung Works flawlessly 😍

**Pull request closed without merging**
