### PR TITLE
docs: Add Japanese docs.

### PR DESCRIPTION
**Pull request by coji**
Add the Japanese version of the documentation to `docs/ja`.

I really want to be able to switch between the two in the [conform.guide](https://conform.guide). However, it's quite complicated, so I'm going to add just the md file so that it can be viewed on github.

I wrote the commit comment in detail in Japanese, so it would be good if you could squash merge it.

### CODE REVIEW

**Comment by edmundhung** [comment]
Hi @coji, really appreciate your effort on translating all the docs! 

I am a little concern about keeping the translated docs up-to-dated with the english one going forward. I am happy to merge your PR as is, but I am just wondering if it would be a better idea if I should provide a link to your translated copy instead if you have keep it somewhere else. What do you think?

**Comment by coji** [comment]
@edmundhung Thanks for your feedback. I agree that maintaining the Japanese documentation separately might be a better approach. I will fork the repository and prepare a page for the Japanese version while keeping it up to date. Once everything is set up, I will reach out to you again to discuss further.

**Comment by edmundhung** [comment]
Thanks @coji :) Feel free to DM me on twitter if you need anything from my side.

Also, I found this [link](https://zenn.dev/coji/books/conform-guide) you shared on twitter. Is this the right place to link to for the Japanese translation? 🙌🏼

**Comment by coji** [comment]
@edmundhung Thank you for your support.

The site I shared on Twitter was manually created, making it difficult to update, so it would be better not to use that link.

For future updates, I have translated the content of the guide directory into Japanese and included the Japanese md files in a fork of this repository. I've prepared a site on Cloudflare Pages based on the content of the forked repository.

I believe linking to https://conform-guide-jp.pages.dev/ would be best.

The forked repository/branch is as follows. I plan to update it as needed in the future.
https://github.com/coji/conform/tree/feat/guide-in-ja-JP

**Comment by edmundhung** [comment]
I don't think I could point the domain to your cloudflare account because of the way Cloudflare pages is configure through its custom proxy. 

As an alternative, how about pushing all the translations to a branch called `jp` in the official repo? In this case, Cloudflare Pages will autoamtically publish it to `https://jp.conform.pages.dev` and I can even add an alias to make it `https://jp.conform.guide`. Once I figure out the permission setting, I can also give you dedicate access to push to the JP branch directly if you are willing to help maintaining the translation :)

**Comment by coji** [comment]
@edmundhung Thank you for the alternative suggestion. Creating a separate branch in the official repository and pushing the translations there sounds like an excellent idea.

If I may suggest, using ja instead of jp for the branch name would be more appropriate, as it aligns with the [ISO language code](https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes) for Japanese.

It's really convenient that Cloudflare Pages will automatically publish the content to https://ja.conform.pages.dev. Moreover, adding an alias like https://ja.conform.guide would make it even more user-friendly and accessible for Japanese users.

Regarding the maintenance of the translations, I'd be more than happy to help. If you can provide me with direct push access to the ja branch, I can keep the Japanese documentation up to date whenever there are updates to the English version.

This approach allows us to provide the Japanese documentation without modifying the main repository, which seems ideal. I appreciate your willingness to handle the permission settings and any other necessary arrangements.

I'm excited to contribute to the community by helping maintain the translations. Please let me know if there's anything else I can assist with.

Thank you once again for the collaboration and support!

**Comment by edmundhung** [comment]
Sounds good to me. Should I reopen this PR and merge it into the `ja` branch or if you would like to create a new PR?

**Comment by coji** [comment]
@edmundhung. 

I've created a new PR for the `ja` branch target here. Please review.
https://github.com/edmundhung/conform/pull/536

**Pull request closed without merging**
