### PR TITLE
feat(conform-zod): auto type coercion

### LINKED ISSUE #219: Introspect the Zod schema to make array inputs always arrays
There's this caveat in the form guide:

> Conform will transform the value to an array only when there are more than one files selected. To ensure a consistent data structure, you need to preprocess the data as shown in the snippet.

I would like it very much if Conform were to introspect the Zod schema for this. If I expect something to be an array, turn it into one even if only one value was submitted. I did this in my own version of the parser and it was annoying but it worked well: https://github.com/epicweb-dev/rocket-rental/blob/a85622e0539b84f2ff06f4c9aee472e328f9052e/app/utils/forms.tsx#L340

### PR DESCRIPTION
**Pull request by edmundhung**
Fix #219, #107, #175

This enables auto type coercion by recreating the complete schema with an extra `z.preprocess()` setup on each primitive type. It will strip the empty value with automatic type coercion based on the schema type.

If this is merged, the new `stripEmptyValue` option introduced on #224 is no longer necessary.

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'd love to bring in @colinhacks and @JacobWeisenburger to ask their opinion on how bad it is to interpolate the zod schema. It would *drastically* improve things for users of Conform (among other libraries I know), but it's a pseudo-private API that I think would be a shame to have broken.

**Review by kentcdodds — APPROVED** [review]
I feel pretty good about the implementation and the way it improves the schemas in the tests is only a small taste of how much nicer this will be :)

**Comment by JacobWeisenburger** [comment]
@kentcdodds, what do you mean by "interpolate the zod schema"? What are you interpolating the schema to?

**Comment by kentcdodds** [comment]
Sorry @JacobWeisenburger, I meant "introspect the zod schema" 🤦‍♂️

Here @edmundhung is looking through the zod schema to determine how to transform it to handle `FormData` nicely.

**Comment by JacobWeisenburger** [comment]
@kentcdodds, as far as I know, it's not bad to use the pseudo-private properties as read only. You will likely have problems if you try to write to them. Does that answer your question?

**Comment by kentcdodds** [comment]
Yep, thanks @JacobWeisenburger.

I say let's do it @edmundhung 👍

**Pull request merged**
