### PR TITLE
fix(conform-zod): do not coerce whitespace to 0

### LINKED ISSUE #333: Whitespace chars in number fields are incorrectly coerced to 0 with zod
### Describe the bug and the expected behavior

When using z.number() with @conform-to/zod, whitespace characters, e.g. `" "` are incorrectly coerced to 0 by the enableTypeCoercion fn. The problem is that the JS `Number` function handles whitespace characters as 0. A fix would be to use `parseFloat` instead of `Number` on [L124](https://github.com/edmundhung/conform/blob/main/packages/conform-zod/coercion.ts#L124).

### Conform version

v0.9.0

### Steps to Reproduce the Bug or Issue

1. Create a number field which is validated with z.number()
2. Add whitespace characters, e.g. `"   "`
3. Validation passes and the input value is coerced to `0`. Validation should fail instead.

### What browsers are you seeing the problem on?

_No response_

### Screenshots or Videos

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by marcomuser**
Fixes #333

### CODE REVIEW

**Comment by marcomuser** [comment]
While this would fix #333, seems like there are more considerations to handle according to the tests... 🤔

**Comment by marcomuser** [comment]
Updated the PR to keep the Number fn to coerce the input but added an additional check to handle white space characters only user input. I also added a simple test to check for this case. What do you think? :-)

**Review by edmundhung — APPROVED** [review]
Thanks you! I think it makes sense to add an extra check for whitespace. This should be good enough for simple usage. If anyone want a more custom parsing logic, they should just use `z.preprocess` or `z.transform()`.

**Comment by edmundhung** [comment]
Sorry for holding up this PR for so long. The change will be available on v1. Thanks again and happy new year!

**Pull request merged**
